apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudmart-backend-app
  template:
    metadata:
      labels:
        app: cloudmart-backend-app
    spec:
      serviceAccountName: cloudmart-pod-execution-role
      containers:
      - name: cloudmart-backend-app
        image: 171756463090.dkr.ecr.us-east-1.amazonaws.com/cloudmart-backend:latest
        env:
        - name: PORT
          value: "5000"
        - name: AWS_REGION
          value: "us-east-1"
        - name: BEDROCK_AGENT_ID
          value: "98RJJL7JOG"
        - name: BEDROCK_AGENT_ALIAS_ID
          value: "FZSIWEA5H0"
        - name: OPENAI_API_KEY
          value: "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"
        - name: OPENAI_ASSISTANT_ID
          value: "asst_0iviM3t3CvEIyFg7qLnZZss2"
---

apiVersion: v1
kind: Service
metadata:
  name: cloudmart-backend-app-service
spec:
  type: LoadBalancer
  selector:
    app: cloudmart-backend-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
